<?php

namespace Database\Seeders;

use App\Models\Block;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Block::truncate();
        $blocks=[
            [
                'id'=>1,
                'block_name'=>'AIBAWK',
                'block_lgd_code'=>'2387',
                'district_id'=>1,
            ],
            [
                'id'=>2,
                'block_name'=>'DARLAWN',
                'block_lgd_code'=>'2388',
                'district_id'=>1,
            ],
            [
                'id'=>3,
                'block_name'=>'THINGSULTHLIAH',
                'block_lgd_code'=>'2390',
                'district_id'=>1,
            ],
            [
                'id'=>4,
                'block_name'=>'THLANGNUAM',
                'block_lgd_code'=>'2391',
                'district_id'=>1,
            ],
            [
                'id'=>5,
                'block_name'=>'BUNGHMUN',
                'block_lgd_code'=>'2400',
                'district_id'=>2,
            ],
            [
                'id'=>6,
                'block_name'=>'LUNGLEI',
                'block_lgd_code'=>'2402',
                'district_id'=>2,
            ],
            [
                'id'=>7,
                'block_name'=>'LUNGSEN',
                'block_lgd_code'=>'2403',
                'district_id'=>2,
            ],
            [
                'id'=>8,
                'block_name'=>'SAIHA',
                'block_lgd_code'=>'2407',
                'district_id'=>3,
            ],
            [
                'id'=>9,
                'block_name'=>'TUIPANG',
                'block_lgd_code'=>'2409',
                'district_id'=>3,
            ],
            [
                'id'=>10,
                'block_name'=>'CHAMPHAI',
                'block_lgd_code'=>'6520',
                'district_id'=>4,
            ],
            [
                'id'=>11,
                'block_name'=>'KHAWBUNG',
                'block_lgd_code'=>'2392',
                'district_id'=>4,
            ],
            [
                'id'=>12,
                'block_name'=>'BILKHAWTHLIR',
                'block_lgd_code'=>'6521',
                'district_id'=>5,
            ],
            [
                'id'=>13,
                'block_name'=>'THINGDAWL',
                'block_lgd_code'=>'2395',
                'district_id'=>5,
            ],
            [
                'id'=>14,
                'block_name'=>'EAST LUNGDAR',
                'block_lgd_code'=>'6519',
                'district_id'=>6,
            ],
            [
                'id'=>15,
                'block_name'=>'SERCHHIP',
                'block_lgd_code'=>'6516',
                'district_id'=>6,
            ],
            [
                'id'=>16,
                'block_name'=>'BUNGTLANG SOUTH',
                'block_lgd_code'=>'2396',
                'district_id'=>7,
            ],
            [
                'id'=>17,
                'block_name'=>'CHAWNGTE',
                'block_lgd_code'=>'2397',
                'district_id'=>7,
            ],
            [
                'id'=>18,
                'block_name'=>'LAWNGTLAI',
                'block_lgd_code'=>'2398',
                'district_id'=>7,
            ],
            [
                'id'=>19,
                'block_name'=>'SANGAU',
                'block_lgd_code'=>'2399',
                'district_id'=>7,
            ],
            [
                'id'=>20,
                'block_name'=>'REIEK',
                'block_lgd_code'=>'2404',
                'district_id'=>8,
            ],
            [
                'id'=>21,
                'block_name'=>'WEST PHAILENG',
                'block_lgd_code'=>'2405',
                'district_id'=>8,
            ],
            [
                'id'=>22,
                'block_name'=>'ZAWLNUAM',
                'block_lgd_code'=>'2406',
                'district_id'=>8,
            ],
            [
                'id'=>23,
                'block_name'=>'NGOPA',
                'block_lgd_code'=>'2394',
                'district_id'=>9,
            ],
            [
                'id'=>24,
                'block_name'=>'PHULLEN',
                'block_lgd_code'=>'2389',
                'district_id'=>9,
            ],
            [
                'id'=>25,
                'block_name'=>'KHAWZAWL',
                'block_lgd_code'=>'2393',
                'district_id'=>10,
            ],
            [
                'id'=>26,
                'block_name'=>'HNAHTHIAL',
                'block_lgd_code'=>'2401',
                'district_id'=>11,
            ],
        ];
        foreach ($blocks as $block){
            Block::query()->create($block);
        }
    }
}
